// VER-DÉ 2.0 discovery catalog. Values omitted by production remain blank.
const catalog = [
  {id:'bagsak',title:'BAGSAK',runtime:'',language:['Tagalog','English'],filmmaker:'Green Ralph',countryLocation:'Nabua, Camarines Sur, Philippines',genre:[],themes:['childhood','family','judgement','life'],mood:[],subject:'A childhood report card and four family voices judging a man across his life.',setting:'',synopsis:'Thirty-nine years of being told what I am. This is year forty. One report card. Four voices. No reply.',access:'free',award:'',format:'16:9 full cut',videoId:'jYSCtwO8t_o',playback:'single'},
  {id:'sentensyador',title:'SENTENSYADOR',runtime:'2:03',language:['Tagalog','English'],filmmaker:'Green Ralph',countryLocation:'Nabua, Camarines Sur, Philippines',genre:[],themes:['judgement','endurance'],mood:[],subject:'A man sentenced by everyone who knows him.',setting:'',synopsis:'A man is sentenced by everyone who knows him. He does not argue. He shrugs, and walks.',access:'free',award:'Official Film Entry · SINE AI × CapCut',format:'',videoId:'4eCo3NZvG14',playback:'single'},
  {id:'project-39-rebuild',title:'PROJECT 39: REBUILD',runtime:'',language:['Tagalog','English'],filmmaker:'Green Ralph',countryLocation:'Nabua, Camarines Sur, Philippines',genre:[],themes:['loss','farm','land','rebuilding','community'],mood:[],subject:'A Filipino man returns to the land after losing his restaurant and his farm’s promise.',setting:'Farm',synopsis:'A Filipino man loses everything — his restaurant, his farm’s promise — mocked by his father, his relatives, his community. He returns to the only thing that still asks nothing of him: the land.',access:'founding',award:'GAIC 2026 · Top 10 Finalist',format:'',videoId:'yBTwnDkEcOc',playback:'single'},
  {id:'the-storm-answers',title:'THE STORM ANSWERS',runtime:'',language:['English'],filmmaker:'Green Ralph',countryLocation:'Nabua, Camarines Sur, Philippines',genre:['Hybrid documentary'],themes:['storm','loss','faith','farming'],mood:[],subject:'A farmer speaks to God after a storm.',setting:'Farm; Typhoon Kristine footage',synopsis:'A farmer loses everything to the storm and screams at God. The storm answers back in questions.',access:'founding',award:'',format:'Hybrid documentary',videoId:'55-tFh4IAzA',playback:'single'},
  {id:'maraming-kamay',title:'MARAMING KAMAY',runtime:'',language:['Tagalog','English'],filmmaker:'Green Ralph',countryLocation:'Nabua, Camarines Sur, Philippines',genre:[],themes:['land','inheritance','family','archive'],mood:[],subject:'The family hands that worked the ground before him.',setting:'Family archive; land',synopsis:'You will not inherit this land. You will only borrow it. Like me.',access:'founding',award:'',format:'',videoId:'zdYKfAKUkPg',playback:'single'},
  {id:'the-wilderness-original',title:'THE WILDERNESS — 16:9 original',runtime:'',language:['Tagalog','English'],filmmaker:'Green Ralph',countryLocation:'Nabua, Camarines Sur, Philippines',genre:[],themes:['childhood','guardian','dry years','Project 39'],mood:[],subject:'The guardian walking beside a child through the dry years.',setting:'',synopsis:'Project 39, Chapter II. The guardian that walks beside a child through the dry years.',access:'founding',award:'AIMV 2026 Excellent Finalist',format:'16:9 original',videoId:'WOD2cUUMFuQ',playback:'single'},
  {id:'the-wilderness-vertical',title:'THE WILDERNESS — 9:16 vertical',runtime:'',language:['Tagalog','English'],filmmaker:'Green Ralph',countryLocation:'Nabua, Camarines Sur, Philippines',genre:[],themes:['childhood','guardian','dry years','Project 39'],mood:[],subject:'The vertical cut of Project 39, Chapter II.',setting:'',synopsis:'Project 39, Chapter II. The guardian that walks beside a child through the dry years.',access:'founding',award:'',format:'9:16 vertical cut',videoId:'yIreldc7cIA',playback:'vertical'},
  {id:'proof-of-presence',title:'PROOF OF PRESENCE',runtime:'',language:['English'],filmmaker:'Green Ralph',countryLocation:'Nabua, Camarines Sur, Philippines',genre:[],themes:['work','presence'],mood:[],subject:'Evidence of someone continuing to work unseen.',setting:'',synopsis:'Evidence that someone was here, and kept working, when nobody was watching.',access:'founding',award:'',format:'',videoId:'H_jKj8FZq10',playback:'single'},
  {id:'project-39-35',title:'PROJECT 39 — EP. 35: BUHAY',runtime:'',language:['Tagalog','English'],filmmaker:'Green Ralph',countryLocation:'Nabua, Camarines Sur, Philippines',genre:[],themes:['Project 39'],mood:[],subject:'',setting:'',synopsis:'',access:'founding',award:'',format:'Vertical series episode',videoId:'ULYcM3dFzcw',playback:'vertical'},
  {id:'project-39-34',title:'PROJECT 39 — EP. 34: BALIK',runtime:'',language:['Tagalog','English'],filmmaker:'Green Ralph',countryLocation:'Nabua, Camarines Sur, Philippines',genre:[],themes:['Project 39'],mood:[],subject:'',setting:'',synopsis:'',access:'founding',award:'',format:'Vertical series episode',videoId:'P5OtJTIG0ks',playback:'vertical'},
  {id:'project-39-33',title:'PROJECT 39 — EP. 33: A FILM THAT NEVER HAPPENED',runtime:'',language:['Tagalog','English'],filmmaker:'Green Ralph',countryLocation:'Nabua, Camarines Sur, Philippines',genre:[],themes:['Project 39'],mood:[],subject:'',setting:'',synopsis:'',access:'founding',award:'',format:'Vertical series episode',videoId:'Ge2qq4j-f00',playback:'vertical'},
  {id:'project-39-32',title:'PROJECT 39 — EP. 32: WHAT THE FIELD GIVES',runtime:'',language:['Tagalog','English'],filmmaker:'Green Ralph',countryLocation:'Nabua, Camarines Sur, Philippines',genre:[],themes:['Project 39'],mood:[],subject:'',setting:'',synopsis:'',access:'founding',award:'',format:'Vertical series episode',videoId:'i6G54cSTQMw',playback:'vertical'},
  {id:'project-39-31',title:'PROJECT 39 — EP. 31: REBUILD // BODY',runtime:'',language:['Tagalog','English'],filmmaker:'Green Ralph',countryLocation:'Nabua, Camarines Sur, Philippines',genre:[],themes:['Project 39'],mood:[],subject:'',setting:'',synopsis:'',access:'founding',award:'',format:'Vertical series episode',videoId:'89CfeisPhlc',playback:'vertical'},
  {id:'project-39-30',title:'PROJECT 39 — EP. 30: ONE MORE LOAD',runtime:'',language:['Tagalog','English'],filmmaker:'Green Ralph',countryLocation:'Nabua, Camarines Sur, Philippines',genre:[],themes:['Project 39'],mood:[],subject:'',setting:'',synopsis:'',access:'founding',award:'',format:'Vertical series episode',videoId:'rTMsH0Q7J5w',playback:'vertical'},
  {id:'project-39-29',title:'PROJECT 39 — EP. 29: ANOTHER LAYER',runtime:'',language:['Tagalog','English'],filmmaker:'Green Ralph',countryLocation:'Nabua, Camarines Sur, Philippines',genre:[],themes:['Project 39'],mood:[],subject:'',setting:'',synopsis:'',access:'founding',award:'',format:'Vertical series episode',videoId:'MvoThE55rcQ',playback:'vertical'},
  {id:'project-39-28',title:'PROJECT 39 — EP. 28: THE COMPOST PIT',runtime:'',language:['Tagalog','English'],filmmaker:'Green Ralph',countryLocation:'Nabua, Camarines Sur, Philippines',genre:[],themes:['Project 39'],mood:[],subject:'',setting:'',synopsis:'',access:'founding',award:'',format:'Vertical series episode',videoId:'SqZV6giZwng',playback:'vertical'},
  {id:'project-39-four-movements',title:'PROJECT 39: FOUR MOVEMENTS',runtime:'6:59',language:[],filmmaker:'Green Ralph',countryLocation:'Nabua, Camarines Sur, Philippines',genre:[],themes:['fall','purgatory','farm','restaurant','broken but alive'],mood:[],subject:'The first telling of the arc through four songs.',setting:'',synopsis:'The fall, purgatory, the farm, the restaurant. Four songs, before any of it had a name. The first telling.',access:'founding',award:'',format:'Vertical · 6:59',videoId:'pydgg2xGePo',playback:'rail'}
];
